### ISSUE TITLE
Misleading APT_SERVICES_CONFIG title

### ISSUE THREAD

**Issue by cdahlhausen** [APTrust/preservation-services#11]
The variable title APT_SERVICES_CONFIG suggests it requires defining a specific configuration file. The expected value however is a environment, hence naming the variable APT_ENVIRONMENT or APP_ENV or APT_ENV may be a more prudent choice.

**Comment by diamondap** [comment]
Should be fixed in https://github.com/APTrust/preservation-services/commit/b4af44b7ba7d6f994ccad3d9aceea83393368108

**Comment by cdahlhausen** [comment]
Confirmed fixed.
